### ISSUE TITLE
Is there a way to access the object returned by function in Javascript box directly inside <script> tag in Template section

### ISSUE THREAD

**Issue by evanceheallyg** [PhaedrusTheGreek/transform_vis#9]
@PhaedrusTheGreek... Is there a way to access the object returned by function in Javascript box directly inside <script> tag in Template section. We need the response returned from ES query to be used as an data source for d3 charts used in the Template section. Any thoughts?

**Comment by YanekR** [comment]
Hi, 

How dod you implement d3 charts to this plugin? Will appreciate a small intro to HOWTO :)

Thanks,
Jan

**Comment by PhaedrusTheGreek** [comment]
Due to security changes, it's no longer possible to get the browser to execute injected script tags without an explicit `eval()` on the contents, which is a too hacky.   Better to isolate all runnable javascript in one place anyhow.

The discussion [here](https://github.com/PhaedrusTheGreek/transform_vis/issues/1) outlines changes that were made today to make D3 work, along with [an example](https://github.com/PhaedrusTheGreek/transform_vis/blob/master/RECIPES.md#custom-d3).
